### ISSUE TITLE
Compute grain volumes from map file

### ISSUE THREAD

**Issue by jadball** [FABLE-3DXRD/xfab#10]
Is there a way that we can calculate grain volumes from an input .map file?

That way, we can add a column to the gff output in ubi_to_gff.py with the grain volumes included.

It looks like the volume is at least estimated in ImageD11/scripts/plotImageD11map.py but perhaps this is relative and not absolute?

**Comment by jonwright** [comment]
It is relative and not absolute. If you assume all grains are indexed you can try to use the illuminated sample volume and fraction of intensity that was indexed to try to make the relative values absolute. 

Historically there was some work where people measured foils of known thickness to normalise the counts on the detector into absolute electron units. Scanning a small beam across a grain to get the size, or imaging the shapes directly might be easier.

**Comment by jadball** [comment]
Understood, thank you. Unfortunately this is not an assumption that we can make here.
I will alter my analysis accordingly.
