### ISSUE TITLE
Checking U matrices are rotations ?

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/xfab#14]
Functions like u_to_rod and u_to_euler are susceptible to garbage in -> garbage out problems if the supplied matrix is not a rotation. Unclear whether this can be fixed without causing a slowdown.

**Comment by AxelHenningsson** [comment]
Adding an assertion statement into u_to_euler.py right at the top for protection like:
`assert np.allclose( np.dot(U.T, U), np.eye(3,3) ), "Input matrix is not unitary."`
seems to give about a 3-4 times slowdown. However we are talking 5.2e-5s vs 1.5e-5s. So it all depends on application. Since the functions are not compiled in the first place I guess speed is not an issue?

```
import time
import numpy as np

def get_unitary_matrix():
    U = np.random.rand(3,3)
    U[:,0] = U[:,0] - U[:,0].dot( U[:,1] ) * U[:,1] / np.linalg.norm(U[:,1])**2
    U[:,2] = np.cross(U[:,0], U[:,1])
    return  U / np.linalg.norm(U, axis=0)

tottime = 0
samples  = 5000
for _ in range(samples):
    U = get_unitary_matrix()
    t1 = time.process_time()
    u_to_euler( U )
    t2 = time.process_time()
    tottime += t2 - t1
print(tottime/samples)
```

**Comment by jonwright** [comment]
Stackoverflow suggests we also need `det(U)==1` to avoid mirror plane operations? I was not sure whether we could just check that `euler_to_u` gives back the input??

If we can do this via a decorator, we could make the argument check or return value check somehow optional. There are also new options for static typing (that I have not yet learned to use) that seem like they could be useful.

For the speed, I guess there is a lot to gain from tools like this https://numba.pydata.org/numba-doc/latest/user/jit-module.html

**Comment by AxelHenningsson** [comment]
Going for 
`assert np.allclose( euler_to_u( phi1, PHI, phi2 ), U ), "Input matrix is not a rotation matrix."`
at the end of the function seems to be slower, I get a timing of 7.5e-4.

det(U)==1 is inferred form U.T.dot(U)==eye(3,3) right? Thinking
`det( U.T.dot(U)) = det(U.T)*det(U) = det(eye(3,3)) = 1   =>  det(U)=det(U.T)=1`

Tried to jit decorate the functions but they actually seemed to get slower by that. 

Making the check optional seems to be a smart choice, decorator might be a bit fancy though, I would go for something like

```
def u_to_euler(U, check_input=False):

    if check_input:
        assert np.allclose( np.dot(U.T, U), np.eye(3,3) ), "Input matrix is not unitary."
   ...

```
The if statement is basically free to evaluate maintaining speed for` check_input=False`. If one wants to implement the like across the board it might be nice to put the various checks in boolean functions getting called like `check_unitary(matrix, check_input)`

**Comment by AxelHenningsson** [comment]
What do you think of this type of implementation?:
```
CHECK_INPUT = False # if set to true all tools functions will run checks to catch bad input but be slower.

def check_euler_angles(phi1, PHI, phi2, check_input):
    if check_input:
        assert 0<=phi1 and  phi1<=np.pi*2, "Euler angle phi1 out of range 0 to 2 pi"
        assert 0<=PHI  and  PHI<=np.pi*2,  "Euler angle PHI out of range 0 to 2 pi""
        assert 0<=phi2 and  phi2<=np.pi*2, "Euler angle phi2 out of range 0 to 2 pi"" 

def euler_to_u(phi1: float, PHI: float, phi2: float, check_input: bool=CHECK_INPUT) -> n.array:
    """
    U matrix from Euler angles phi1, PHI, phi2.
    The formalism follows the ID11-3DXRD specs
    
    U = euler_to_u(phi1, PHI, phi2)
    
    INPUT: phi1, PHI, and phi2 angles in radians
    OUTPUT: U = array([[U11, U12, U13],[ U21, U22, U23],[U31, U32, U33]])
    
    Changed input angles to be in radians instead of degrees
    Henning Osholm Sorensen, Riso National Laboratory, June 23, 2006.
    
    Translated from MATLAB to python by Jette Oddershede, March 26 2008
    Origingal MATLAB code from: Henning Poulsen, Risoe 15/6 2002.
    
    """
    check_euler_angles(phi1, PHI, phi2, check_input)

    U = n.zeros((3, 3))
    U[0, 0] =   n.cos(phi1)*n.cos(phi2)-n.sin(phi1)*n.sin(phi2)*n.cos(PHI)
    U[1, 0] =   n.sin(phi1)*n.cos(phi2)+n.cos(phi1)*n.sin(phi2)*n.cos(PHI)
    U[2, 0] =   n.sin(phi2)*n.sin(PHI)
    U[0, 1] =  -n.cos(phi1)*n.sin(phi2)-n.sin(phi1)*n.cos(phi2)*n.cos(PHI)
    U[1, 1] =  -n.sin(phi1)*n.sin(phi2)+n.cos(phi1)*n.cos(phi2)*n.cos(PHI)
    U[2, 1] =   n.cos(phi2)*n.sin(PHI)
    U[0, 2] =   n.sin(phi1)*n.sin(PHI) 
    U[1, 2] =  -n.cos(phi1)*n.sin(PHI)
    U[2, 2] =   n.cos(PHI)
    return U
```
Then one can go `xfab.tools.CHECK_INPUT=True` to toggle all on all checkers but also check for specific cases. This would also be compatible with any existing code, as the default behavior is just as before.

**Comment by jonwright** [comment]
Looks promising. For the checks ... maybe it is simpler to just using `assert` or `if __debug__:` together with a comment telling people to use `python -O` or set `PYTHONOPTIMIZE` if they want to avoid the slow down effect from these sanity checks ? 

Having the default as "safe + correct" is probably a good policy, most of the xfab code is not optimised anyway (`euler_to_u` might go a little faster if it computes the sin/cos values once and then re-uses them??)

I guess the type checking on arguments is only for recent pythons? If we use this we ought to modify setup.py to prevent it installing on python2 from pip/pypi. For fabio it needed a 'python_requires' to be set (https://github.com/silx-kit/fabio/pull/382/commits/e3d4832e9994e11841e98faba87d1680931ab86e).

For the det(U) story, I think a mirror plane looks like this:
```
>>> u = numpy.array( [[1,0,0],[0,1,0],[0,0,-1]] )
>>> numpy.linalg.det(u)
-1.0
>>> numpy.dot( u.T, u )
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
>>>
```
I assume you can't get a set of Euler angles for this, but using a mirror twice does take us back to the start point with an identity.

**Comment by AxelHenningsson** [comment]
Ah see what you mean with the determinant. Could be either +1 or -1.
`det( U.T.dot(U)) = det(U.T)*det(U) = det(eye(3,3)) = 1 => det(U)=det(U.T)=+-1`
I like the `CHECK_INPUT = False` approach since it gives more control. (or default `CHECK_INPUT = True` for "safe + correct"  policy). But I guess its mostly preferences.

**Comment by AxelHenningsson** [comment]
If you have a design preference I  can go ahead and draft a pull request for us. 

Cheers
Axel

**Comment by jonwright** [comment]
Thanks Axel !  I am thinking the "default" should be correctness for python code, so the checks should probably go in somehow to help out beginners. Keeping python2 compatibility is useful for getting errorbars out of fitallb.

Then there is a question of one global for the whole program (`__debug__` or assert) versus one global for the library/module versus an optional default argument on the function. Maybe this is covered by:

```
def u_to_euler( U, verify = True ):
    assert (verify and is_rotation(U) ), "problem with U matrix"
    .... 
    assert (verify and np.allclose( U, euler_to_u( *return_value )  ) ), "problem computing euler angles"
```

I'm not sure how readable this is? It should skip both tests when run under `python -O` or short circuit and skip the test when verify is false (probably needs a check). We could introduce a module level `xfab.verify` to then scatter these kinds of tests all over the code and turn them on and off in one place.

**Comment by AxelHenningsson** [comment]
Ok, time to get this done, I will take myself some artistic freedom while doing this. Just want to mention that I really strongly think that things like
`assert (verify and np.allclose( U, euler_to_u( *return_value )  ) )"`
should go in the **unit tests** as it is nothing to do with the user. I.e the unit tests should have already verified that if input in is good, then output is **guaranteed** to be good. Input checking is legit though.
