### ISSUE TITLE
Set up a CI

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/xfab#16]
... for running unit tests automagically

**Comment by AxelHenningsson** [comment]
I am on this...

...it appears flake8 is telling us there is broken zombie code inside xfab:
![image](https://user-images.githubusercontent.com/31615210/151015459-3cc5c7ef-06c6-4174-bb1c-135bd85fc1f3.png)
Will open a pull request to fix this.

(I am currently staying away from failing on bad pep8 standards with flake8 calls as that would be a major style project to get onto, and it does not really matter for the package functionality. But broken code we should probably fix. )

**Comment by AxelHenningsson** [comment]
`print(a,b)` still works on python 2.7 and python 3.x right? I will leave the folder for you to delete. (Feel a bit uneasy about deleting stuff...hehe ^^). The command

`flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics`

Seems to be similar to what the code in the linting folder is doing. If we want to restyle the code I think we should use [autopep8](https://pypi.org/project/autopep8/)

**Comment by AxelHenningsson** [comment]
Ok so the linux build is now successful using
```
  pip install numpy six pycifrw
  python setup.py install
```
Ideally we would like to have a workflow that installs from pip. I love to update the pypi channels if it is possible to share privileges in a safe way.

**Comment by jonwright** [comment]
I just added the import to enable `print(a,b)` to work on 2.7 - hopefully - I now need to find an old install somewhere.

There was a bit of noise about these autoformatting things recently - they make me nervous if we do not have test coverage and do not check for 2.7 : https://twitter.com/raymondh/status/1482225220475883522

If you have a pypi username I can add you as a collaborator there.

**Comment by AxelHenningsson** [comment]
My pypi user name is **Axiomel**.

Yeah the low unittest coverage and python 2.7 compatibility makes me a bit nervous in general too.

**Comment by AxelHenningsson** [comment]
And now we have python 3.9 automatic installation and pytest on macos and ubuntu triggering on push. 🥳 

[![macos-latest, pip install and pytest](https://github.com/FABLE-3DXRD/xfab/actions/workflows/install-and-test-macos-py39.yml/badge.svg)](https://github.com/FABLE-3DXRD/xfab/actions/workflows/install-and-test-macos-py39.yml) [![ubuntu-latest, pip install and pytest](https://github.com/FABLE-3DXRD/xfab/actions/workflows/install-and-test-ubuntu-py39.yml/badge.svg)](https://github.com/FABLE-3DXRD/xfab/actions/workflows/install-and-test-ubuntu-py39.yml)

Maybe we can close this issue now, unless there is anything else in mind for the CI.

**Comment by AxelHenningsson** [comment]
On second thought me might also want to add builds using the setup.py to make sure it is the latest changes to the code we are actually verifying.

**Comment by AxelHenningsson** [comment]
Perhaps something like this is what we want to have: ad2e5c5

**Comment by jonwright** [comment]
Can we add python2.7 and 3.x (or "latest" in a matrix https://github.com/actions/setup-python) ? When 3.11 comes I fear something will break. There is a story about dropping distutils from stdlib and pyproject.toml etc.
For the "install" step, I think I used `python3 -m pip install --editable .` for ImageD11. In principle the editable could be dropped, but in practice I prefer having that as an option when I am working myself.

**Comment by AxelHenningsson** [comment]
Does this look good to you? I will go ahead and add tag for the release.

**Comment by jonwright** [comment]
Looks good to me. For the release, did you need to do something like `twine upload` manually?

**Comment by AxelHenningsson** [comment]
Yep. But not anymore with this I think 73a842d. 

Whenever a release is made here the workflow will try and build and upload to pypi.

What I did for this specific one was to build locally and upload with twine.

With that I will close this one 🙂 

Cheers
Axel
