### ISSUE TITLE
Loading CIFs lacking _atom_type_symbol entry.

### ISSUE THREAD

**Issue by AxelHenningsson** [FABLE-3DXRD/xfab#17]
Is it expected that the CIF loading with xfab as below:

```
from xfab import structure
atom_factory = structure.build_atomlist()
atom_factory.CIFread(ciffile = "mycif.cif", cifblkname = None, cifblk = None)
```

should fail if `_atom_type_symbol ` is lacking in while ` _atom_site_type_symbol` is present in the CIF?

The CIF ending like:

```
loop_
 _atom_type_symbol
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Fe  Fe  Fe0  1  0.00000000  0.00000000  0.00000000  1
  Fe  Fe  Fe1  1  0.00000000  0.50000000  0.50000000  1
  Fe  Fe  Fe2  1  0.50000000  0.00000000  0.50000000  1
  Fe  Fe  Fe3  1  0.50000000  0.50000000  0.00000000  1
```

works fine for instance, while the CIF

```
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Fe  Fe0  1  0.00000000  0.00000000  0.00000000  1
  Fe  Fe1  1  0.00000000  0.50000000  0.50000000  1
  Fe  Fe2  1  0.50000000  0.00000000  0.50000000  1
  Fe  Fe3  1  0.50000000  0.50000000  0.00000000  1
```

crashes on read. Altough it seems the `_atom_type_symbol` could be infered from `_atom_site_type_symbol` in this case. Might be this is a simple misunderstanding on how CIFs work., altough any CIFs downloaded from the materials project (https://materialsproject.org/) will not have the `_atom_type_symbol`.  (I suspect this is all happening in `ReadCif()` in the `CifFile `module )

**Comment by jonwright** [comment]
Thanks!
