### ISSUE TITLE
python2.7 parameters/logging issue

### ISSUE THREAD

**Issue by jonwright** [FABLE-3DXRD/xfab#19]
ImageD11 CI fell over:
```
ImageD11\indexing.py:342: in loadpars
    self.parameterobj.update_other(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <xfab.parameters.parameters instance at 0x05380800>
other = <[TypeError("'NoneType' object is not callable") raised in repr()] indexer object at 0x5380580>
    def update_other(self,other):
        """
        Synchronise an object with the values in this object
        """
        for k,v in list(self.parameters.items()):
            if hasattr(other,k):
                var = getattr(other,k)
>               logging.debug("setting: %s.%s from %s to %s"%(other,k,var,v))
E               TypeError: 'NoneType' object is not callable
C:\Miniconda\lib\site-packages\xfab\parameters.py:162: TypeError
---------------------------- Captured stdout call -----------------------------
```

**Comment by AxelHenningsson** [comment]
Any more clues to what is wrong here. Is it something to do with more recent updates to xfab, or is it something in ImageD11. Is the above from a unit test failure in ImageD11, or how can I reproduce this? 🙂 

cheers

**Comment by AxelHenningsson** [comment]
@jonwright I see this was opened over two months ago, combining that fact with the CI status of ImageD11 (which seems good) I am guessing this has been resolved, can we close this thread, and go hunt some other fish? 🙂 🐟 

ID11 status:
![image](https://user-images.githubusercontent.com/31615210/151229290-89ff7bb9-7639-48ee-bf7c-30b70fed83d5.png)

**Comment by jonwright** [comment]
A failure was here:
https://ci.appveyor.com/project/jonwright/imaged11/builds/41814574

Probably the actual problem is here:
https://github.com/jonwright/ImageD11/blob/95bfd1eb8e88714484d19ec1c133a5590b264dda/ImageD11/indexing.py#L318

Maybe that code is setting `__repr__` to `None`. I did not really understand it yet but randomly patched ImageD11 until it went away. For some reason I had thought logging was `None` but I think it is not the answer. Perhaps something like `__slots__` or traits is a better solution to the problem.

Anyway, there is a mix of print functions and logging in `parameters.py` here. If we keep the logging here, we lack the notion of an `xfab` logger versus the global logger (that gets messages about matplotlib fonts for example).

There are also some problems about multiprocessing and logging, so maybe better to just remove all the logging and go for print statements. I would still be worried about an xfab module level global like "verbose" if it causes all the processes to serialise whenever it is read, I had a feeling this kind of configuration is needed at the object level.

**Comment by AxelHenningsson** [comment]
I would love to remove all the logging from xfab, especially if we can add a verbose option instead. Some of the non-optional logging is driving me crazy.

Is serialization of a module level variable a problematic? Either way I guess python must serialize the function itself getting called in parallel? Is that not more of a memory problem, so if the things we serialize is small, no one will notice?

There is also the option of adding a verbose option to every relevant function in xfab.

**Comment by jonwright** [comment]
Going through all the cases and deciding what do is difficult. It means tracking down the way xfab is using in polyxsim and fitallb too. Maybe we can suppress some noise like this:
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

Might be just this in `__init__.py` ??:
```
import logging
logging.getLogger(__name__).addHandler(logging.NullHandler())
```
Some multiprocessing issues might remain (https://bugs.python.org/issue6721). The idea of the logging was meant to clean up the "global verbose + print" in a better way, so users could optionally look into some more detailed output when running a gui program. Also a gui could capture the output.

Using print is really awful when you end up hacking on sys.stdout to turn the printing on and off. But print is probably right for the things in scripts.

To get a really detailed output of what a program did (for reproducible research) then having lots of logging.info could be a useful thing for making logfiles.

**Comment by AxelHenningsson** [comment]
I think this could be a nice way to go: #25

**Comment by AxelHenningsson** [comment]
As an example of the changes in #25. If one goes:
```python
import xfab
from xfab import structure
mylist = structure.build_atomlist()
mylist.CIFread('SiO2_mp-7000_conventional_standard.cif')
```
The usual output now specifies the module as
```
2022-01-28 11:45:05,092 - xfab.structure - WARNING - No _atom_type_symbol found in CIF
2022-01-28 11:45:05,092 - xfab.structure - WARNING - No dispersion factors for Si in cif file - set to zero
2022-01-28 11:45:05,094 - xfab.structure - WARNING - No dispersion factors for Si in cif file - set to zero
...
2022-01-28 11:45:05,105 - xfab.structure - WARNING - No dispersion factors for O in cif file - set to zero
2022-01-28 11:45:05,107 - xfab.structure - WARNING - No dispersion factors for O in cif file - set to zero
```
And if we go
```python
import logging
logger = logging.getLogger('xfab.structure')
logger.setLevel(logging.CRITICAL)
```
No output will be written in the above case, again running
```python
mylist = structure.build_atomlist()
mylist.CIFread('SiO2_mp-7000_conventional_standard.cif')
```

**Comment by AxelHenningsson** [comment]
Unless anyone thinks differently I will go ahead and accept the linked pull request and close this issue. 🙂

**Comment by jonwright** [comment]
Looks great to me - go for it !
