### ISSUE TITLE
Optimize xfab

### ISSUE THREAD

**Issue by AxelHenningsson** [FABLE-3DXRD/xfab#27]
In response to [the comment of jonwright](https://github.com/FABLE-3DXRD/xfab/issues/26#issuecomment-1025177687)

Let us have a discussion on the need and strategy for optimising `xfab` here. I am assuming the conversation will mostly be about `xfab.tools`, but let's see where this goes.

**Starting Point:**
     *Is xfab slow? If so: what examples can be given when timings in `xfab` are poor, and what modules are used in these expected use cases?*

*NOTE*: for the math stuff, like in `xfab.tools`, it would make sense to primarily access the fast and compiled `numpy` stuff by vectorizing as much as possible rather than using `numba` or the like.

**Comment by jonwright** [comment]
In general, we would need to look at a profile for the run time for some other code and then decide whether it is worth it and which things are taking time. I remember there are often a lot of numpy array creations and deletions within an inner loop.

The numba code that I put in was to help for FitAllB (I think), but mostly I abandoned the idea of trying to maintain that package. @jadball has been optimising polyxsim to use multiprocessing, but I did not look into what takes up the run time.

As an example, symmetry.Umis that takes a long time if you are matching a lot of grains. I think I re-wrote something for ImageD11/sandbox/match.py but never tried to move it "upstream" here. There is also some code in cImageD11 for misorientation that was not validated yet (I never figured out the symmetry properly).

**Comment by AxelHenningsson** [comment]
Excellent. 🙂 I will go ahead and optimise symmetry.Umis then.

I think it makes sense to optimise as we discover the bottlenecks. Perhaps you know of some other use cases where speed historically has been a problem.

**Comment by jonwright** [comment]
Before you spend a lot of time on it - take a look at https://github.com/FABLE-3DXRD/ImageD11/blob/master/test/test_misori.py and try running with DOPROFILE = True. There is C code in ImageD11/src/closest.c but I suspect it should be possible to beat it using numba because the jit compiles for the current CPU. 

For that code the real problem is sorting out how to do the symmetry properly - there are more than 7 possibilities (trigonal has rhombohedral or hexagonal axis choices, etc).

**Comment by AxelHenningsson** [comment]
Seems it might be hard to beat your pure C-implementations. They also appear to return the minimal trace of misorientation rather than a list in degrees with all possible misorientation. Is imageD11 currently running of these C-implementations or are you using the xfab stuff? Should we change the behaviour here to return the best fit orientation?

Sticking to optimising what is in xfab without changing functionality I can get something like x10-x80 speedups, depending on `crystal_system `. 

In detail when benching:
```
############# B E N C H ################

>> monoclinic  (10000 calls)
OLD symmetry.Umis():  816.94   ms
NEW symmetry.Umis():  59.06    ms
C-implementation:     7.58     ms
NEW symmetry.Umis() speedup: x14.0

>> orthorhombic  (8000 calls)
OLD symmetry.Umis():  2193.57  ms
NEW symmetry.Umis():  58.79    ms
C-implementation:     5.0      ms
NEW symmetry.Umis() speedup: x37.0

>> tetragonal  (6000 calls)
OLD symmetry.Umis():  3458.08  ms
NEW symmetry.Umis():  68.73    ms
C-implementation:     7.02     ms
NEW symmetry.Umis() speedup: x50.0

>> cubic  (3000 calls)
OLD symmetry.Umis():  4524.99  ms
NEW symmetry.Umis():  62.25    ms
C-implementation:     2.06     ms
NEW symmetry.Umis() speedup: x73.0

########################################
```

The implementation looks something like:

```python
def Umis(umat_1, umat_2, crystal_system):
    rot = ROTATIONS[crystal_system]
    return _Umis(umat_1, umat_2, rot)

@njit(fastmath=True)
def _Umis(umat_1, umat_2, rot):
    misorientations = np.zeros((len(rot), 2))
    misorientations[:, 0] = list(range(0, len(rot)))
    for k in range(len(rot)):
        U_new = np.dot(umat_1, rot[k])
        length = (np.sum(umat_2 * U_new) - 1.)/2.
        misorientations[k, 1] = np.arccos(length)*180/np.pi
    return misorientations

ROTATIONS = [None] + [np.ascontiguousarray(rotations(i)) for i in range(1,8)]
```

where `ROTATIONS ` is computed once on module import (as is anyways a static thing...)

**Comment by jonwright** [comment]
As written, I think the code was aiming at metallurgists who have fcc or hcp metals. For someone looking at twinning in minerals it is not ideal.

I suspect the C code was aiming to find the minimal "disorientation" ? I am not really happy with it for now, as it was not generalized for symmetry properly. (At the time I did not figure it out).

For your code I am surprised by this line `np.sum(umat_2 * U_new)`; is that a magic way to get the trace? There might be an `einsum` trick that skips numba too.

Here is a formulation where each different crystal has a different symmetry: https://doi.org/10.1107/S0021889808016373 

Maybe this paper is a better one to try to dig into : https://doi.org/10.1098/rspa.2017.0274, they seem to be saying there are 11 choices of "proper point groups". This drags us into a problematic area that the indexing does not (in general) use intensities. If we only look at peak positions and ignore the intensities then we only see the lattice symmetry. In that case "trigonal" does not appear to exist as one of the options.

Somewhere in there, ideally, I wanted something to handle non-conventional unit cell choices. Crystallographers often like to just give a list of symmetry operators (or generators). Going in that direction, I got stuck figuring out how to derive the point group and lattice symmetries from an arbitrary list of operators. Perhaps better is the enemy of good here, xfab handles symmetry in a more pragmatic way anyway.

**Comment by AxelHenningsson** [comment]
Seems we are *juggling two balls* now, one is a feature request for xfab.symmetry to handle and do some new stuff, and the other is to optimise the current implementation. I guess passing a list of arbitrary point groups and getting back the minimal distance is what we really want in terms of features, perhaps we can open a new issue for that?
```python
np.sum(umat_2 * U_new)
```
is a math trick to get the trace. The alternative is to do
```python
np.trace(np.dot(umat_2, U_new.T))
```
But then you are doing scalar product for a full 3x3 matrix when you really only are going to use the diagonal. Everything gets summed in the end is the idea. This has all been verified on my fork to give the same stuff as the old `Umis` implementation as
```python
from scipy.spatial.transform import Rotation as R
from xfab import symmetry

def test_Umis(crystal_system):
    for crystal_system in range(1,8):
        U1 = R.random(20).as_matrix()
        U2 = R.random(20).as_matrix()
        for u1, u2 in zip(U1, U2):
            m1 = symmetry.Umis(u1, u2, crystal_system)
            m2 = symmetry.Umis_old(u1, u2, crystal_system)
            assert np.max(np.abs(m1 - m2)) < 1e-5, str(np.max(np.abs(m1 - m2)))
```
**BWT:** if you did not know about [`scipy.spatial.transform.Rotation` ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.random.html) : it is simply awesome for rotation stuff 🚀 😃 !

**Comment by jonwright** [comment]
That is a nice math trick. Perhaps it can help to vectorise with numpy (for now I did not figure out the einsum version, but it should exist and might go faster). This is slower than your numba code but does not need to compile:
```
def _Umis(umat_1, umat_2, rot):
    misorientations = np.empty( (len(rot),2))
    lengths = 0.5 * (rot * np.dot( umat_1.T, umat_2 )).sum(axis=(1,2)) - 0.5
    misorientations[:,0] = np.arange(len(rot))
    misorientations[:,1] = np.arccos(lengths.clip(-1,1)) * 180./np.pi # move this to the outer function?
    return misorientations
```

scipy is an ImageD11 dependency because of that Rotation code, amongst other things. If scipy were to be an xfab dependency it might clean up and speed up a few other things too? 

The wider issues about misorientation has some notes tracking it here: https://github.com/FABLE-3DXRD/ImageD11/issues/46

For code optimisations, sometimes it helps to change the api. For this function it should specify u1 and u2 as both being 3x3 rotation matrices. People sometimes want the `disorientation`, e.g. the minimal angle, and they use this for "matching" between two long lists of grains.

**Comment by AxelHenningsson** [comment]
I think it would be very bad practice if we change the API without any deprecation warnings or nothing of the like, for people who depend on `xfab`. Certainly we should add some documentation while we are at it, but changing input and output types of `symmetry.Umis` seems risky. Then I would rather have an additional function `symmetry.Udis` that can take arrays of rotation matrices, if that is what we like to do.

I am working on drafting a pull request at the moment for optimizing `symmetry.Umis` .

Then perhaps we can start a new issue on adding any new functionality.

Cheers 🙂

**Comment by AxelHenningsson** [comment]
Always better to do some improvements than to do nothing. Sadly I had to revert from numba last minute due to poor python 2.7 support 😞 . 

It is still unclear to me what is are standard use cases of the functions in `symmetry`, so a brand new issue discussing this and possibly agreeing on some new features for the module might be nice.
